---
title: "Plot experiment 2 results"
output: html_document
---

## R Markdown



```{r import the AIC, raw error (pred-true) data generated for prudent and myopic at different horizons}

df5 <- read.csv(file ="horizon_5_raw_error_PM.csv")
df20 <- read.csv(file ="horizon_20_raw_error_PM.csv")
df30 <- read.csv(file ="horizon_30_raw_error_PM.csv")
```


```{r plot the grouped bar plot for AIC comparing prudent and myopic estimation models (agent) at prudent and myopic data simulations (trajectory)}
# Prudent Trajectory, or data simulation, for horizons 5 and 30
# subset df5 prudent agent or estimation model, prudent trajectory or data sim model
pp <- subset(df5, model_sel_agent == 'prudent_agent' & model_sim_traj == 'prudent_traj',select=c(true,AIC,model_sel_agent))
pp$model_sel_agent <- gsub("prudent_agent","Prudent",pp$model_sel_agent)
names(pp)[names(pp) == "model_sel_agent"] <- "Estimation Model"
names(pp)[names(pp) == "true"] <- "True Risk Parameter"

# subset df5 prudent trajectory, myopic agent
pm <- subset(df5, model_sel_agent == 'myopic_agent' & model_sim_traj == 'prudent_traj',select=c(true,AIC,model_sel_agent))
pm$model_sel_agent <- gsub("myopic_agent","Myopic",pm$model_sel_agent)
names(pm)[names(pm) == "model_sel_agent"] <- "Estimation Model"
names(pm)[names(pm) == "true"] <- "True Risk Parameter"

hzn5p <- rbind(pp,pm)


# subset df30 prudent agent or estimation model, prudent trajectory or data sim model
pp <- subset(df30, model_sel_agent == 'prudent_agent' & model_sim_traj == 'prudent_traj',select=c(true,AIC,model_sel_agent))
pp$model_sel_agent <- gsub("prudent_agent","Prudent",pp$model_sel_agent)
names(pp)[names(pp) == "model_sel_agent"] <- "Estimation Model"
names(pp)[names(pp) == "true"] <- "True Risk Parameter"

# subset df30 prudent trajectory, myopic agent
pm <- subset(df30, model_sel_agent == 'myopic_agent' & model_sim_traj == 'prudent_traj',select=c(true,AIC,model_sel_agent))
pm$model_sel_agent <- gsub("myopic_agent","Myopic",pm$model_sel_agent)
names(pm)[names(pm) == "model_sel_agent"] <- "Estimation Model"
names(pm)[names(pm) == "true"] <- "True Risk Parameter"

hzn30p <- rbind(pp,pm)


# myopic trajectory, or data simulation, for horizons 5 and 30
# subset df5 myopic agent or estimation model, myopic trajectory or data simulation model
mm <- subset(df5, model_sel_agent == 'myopic_agent' & model_sim_traj == 'myopic_traj',select=c(true,AIC,model_sel_agent))
mm$model_sel_agent <- gsub("myopic_agent","Myopic",mm$model_sel_agent)
names(mm)[names(mm) == "model_sel_agent"] <- "Estimation Model"
names(mm)[names(mm) == "true"] <- "True Risk Parameter"

# subset df5 myopic trajectory,prudent agent
mp <- subset(df5, model_sel_agent == 'prudent_agent' & model_sim_traj == 'myopic_traj',select=c(true,AIC,model_sel_agent))
mp$model_sel_agent <- gsub("prudent_agent","Prudent",mp$model_sel_agent)
names(mp)[names(mp) == "model_sel_agent"] <- "Estimation Model"
names(mp)[names(mp) == "true"] <- "True Risk Parameter"

hzn5m <- rbind(mm,mp)


# subset df30 myopic agent or estimation model, myopic trajectory or data simulation model
mm <- subset(df30, model_sel_agent == 'myopic_agent' & model_sim_traj == 'myopic_traj',select=c(true,AIC,model_sel_agent))
mm$model_sel_agent <- gsub("myopic_agent","Myopic",mm$model_sel_agent)
names(mm)[names(mm) == "model_sel_agent"] <- "Estimation Model"
names(mm)[names(mm) == "true"] <- "True Risk Parameter"

# subset df30 myopic trajectory,prudent agent
mp <- subset(df30, model_sel_agent == 'prudent_agent' & model_sim_traj == 'myopic_traj',select=c(true,AIC,model_sel_agent))
mp$model_sel_agent <- gsub("prudent_agent","Prudent",mp$model_sel_agent)
names(mp)[names(mp) == "model_sel_agent"] <- "Estimation Model"
names(mp)[names(mp) == "true"] <- "True Risk Parameter"

hzn30m <- rbind(mm,mp)
```


```{r plot the grouped bar plot for AIC}
# 
library(tidyr)
library(ggplot2)
library(gtable)
library(patchwork)
library(gridExtra)

x_axis_labels <- pp[,"True Risk Parameter"]

  horizon5p <- ggplot(hzn5p, aes(fill=`Estimation Model`, y=AIC, x=`True Risk Parameter`)) + 
    geom_bar(position="dodge", stat="identity")+ scale_fill_manual(values=c("#003f5c","#ffa600")) +
  theme_classic() + theme(axis.text.x =element_text(angle=45)) +
  scale_x_continuous(labels = x_axis_labels, breaks=x_axis_labels) + 
  labs(title="Horizon 5 Data simulation model: Prudent") +
    ylim(0, max(df5[,"AIC"]))

horizon30p <- ggplot(hzn30p, aes(fill=`Estimation Model`, y=AIC, x=`True Risk Parameter`)) + 
    geom_bar(position="dodge", stat="identity")+ scale_fill_manual(values=c("#003f5c","#ffa600"))+
  theme_classic() + theme(axis.text.x =element_text(angle=45)) +
  scale_x_continuous(labels = x_axis_labels, breaks=x_axis_labels) + 
  labs(title="Horizon 30 Data simulation model: Prudent") +
  ylim(0, max(df30[,"AIC"]))

horizon5m <- ggplot(hzn5m, aes(fill=`Estimation Model`, y=AIC, x=`True Risk Parameter`)) + 
    geom_bar(position="dodge", stat="identity")+ scale_fill_manual(values=c("#003f5c","#ffa600")) +
  theme_classic() + theme(axis.text.x =element_text(angle=45)) +
  scale_x_continuous(labels = x_axis_labels, breaks=x_axis_labels) + 
  labs(title="Horizon 5 Data simulation model: Myopic") +
  ylim(0, max(df5[,"AIC"]))

horizon30m <- ggplot(hzn30m, aes(fill=`Estimation Model`, y=AIC, x=`True Risk Parameter`)) + 
    geom_bar(position="dodge", stat="identity")+ scale_fill_manual(values=c("#003f5c","#ffa600"))+
  theme_classic() + theme(axis.text.x =element_text(angle=45)) +
  scale_x_continuous(labels = x_axis_labels, breaks=x_axis_labels) + 
  labs(title="Horizon 30 Data simulation model: Myopic") +
  ylim(0, max(df30[,"AIC"]))


```


```{r plot the grouped bar plot for AIC}
setEPS()
postscript('AIC_plots_prudent.eps')
final_figure <- grid.arrange(horizon5p,horizon30p, ncol = 1)
dev.off()

setEPS()
postscript('AIC_plots_myopic.eps')
final_figure <- grid.arrange(horizon5m,horizon30m, ncol = 1)
dev.off()


```


```{r define factors for stat analysis}
# For horizon 5
df5$model_sim_traj <- as.factor(df5$model_sim_traj)
df5$model_sel_agent <- as.factor(df5$model_sel_agent)

# For horizon 20
df20$model_sim_traj <- as.factor(df20$model_sim_traj)
df20$model_sel_agent <- as.factor(df20$model_sel_agent)

# For horizon 30
df30$model_sim_traj <- as.factor(df30$model_sim_traj)
df30$model_sel_agent <- as.factor(df30$model_sel_agent)
```


```{r aggregate raw errors (pred-true risk parameter)}
# Horizon 5
agg5 <- aggregate(raw_error ~ model_sim_traj*model_sel_agent,df5, mean)
agg5sd <- aggregate(raw_error ~ model_sim_traj*model_sel_agent,df5, sd)
names(agg5sd)[names(agg5sd) == "raw_error"] <- "Err bar"

agg5$model_sel_agent <- gsub("myopic_agent","Myopic",agg5$model_sel_agent)
agg5$model_sel_agent <- gsub("prudent_agent","Prudent",agg5$model_sel_agent)
agg5$model_sim_traj <- gsub("myopic_traj","Myopic",agg5$model_sim_traj)
agg5$model_sim_traj <- gsub("prudent_traj","Prudent",agg5$model_sim_traj)

names(agg5)[names(agg5) == "model_sel_agent"] <- "Estimation Model"
names(agg5)[names(agg5) == "model_sim_traj"] <- "Data Simulation Model"
names(agg5)[names(agg5) == "raw_error"] <- "Raw Error"

sample_size <- length(x_axis_labels)
agg5sd <- subset(agg5sd,select = c("Err bar"))/sqrt(sample_size)
agg5 <-cbind(agg5, agg5sd)

# Horizon 30
agg30 <- aggregate(raw_error ~ model_sim_traj*model_sel_agent,df30, mean)
agg30sd <- aggregate(raw_error ~ model_sim_traj*model_sel_agent,df30, sd)
names(agg30sd)[names(agg30sd) == "raw_error"] <- "Err bar"

agg30$model_sel_agent <- gsub("myopic_agent","Myopic",agg30$model_sel_agent)
agg30$model_sel_agent <- gsub("prudent_agent","Prudent",agg30$model_sel_agent)
agg30$model_sim_traj <- gsub("myopic_traj","Myopic",agg30$model_sim_traj)
agg30$model_sim_traj <- gsub("prudent_traj","Prudent",agg30$model_sim_traj)


names(agg30)[names(agg30) == "model_sel_agent"] <- "Estimation Model"
names(agg30)[names(agg30) == "model_sim_traj"] <- "Data Simulation Model"
names(agg30)[names(agg30) == "raw_error"] <- "Raw Error"

# Get the standard errors of the means
agg30sd <- subset(agg30sd,select = c("Err bar"))/sqrt(sample_size)
agg30 <-cbind(agg30, agg30sd)


# only keep the prudent data simulation models
agg5 = agg5[-c(1,3),]
horizon5 <- ggplot(agg5,aes(fill=`Data Simulation Model`, y=`Raw Error`, x=`Estimation Model`)) +
  geom_bar( position=position_dodge(), stat="identity",width=0.75)+
  geom_errorbar(aes(x=`Estimation Model`, ymin=`Raw Error`-`Err bar`, ymax=`Raw Error`+`Err bar`), width=0.1,position=position_dodge(1))+
  theme_classic() +
  labs(title="Horizon 5") +
  scale_fill_manual(values=c("#ffa600"))+ylim(min(agg5[,'Raw Error']-agg5[,'Err bar']), max(agg5[,'Raw Error']+agg5[,'Err bar']))

# Only keep the prudent data simulation models
agg30 = agg30[-c(1,3),]
horizon30 <- ggplot(agg30,aes(fill=`Data Simulation Model`, y=`Raw Error`, x=`Estimation Model`)) +
  geom_bar( position=position_dodge(), stat="identity",width=0.75)+
  geom_errorbar(aes(x=`Estimation Model`, ymin=`Raw Error`-`Err bar`, ymax=`Raw Error`+`Err bar`), width=0.1,position=position_dodge(1))+
  theme_classic() +
  labs(title="Horizon 30")+
  scale_fill_manual(values=c("#ffa600"))+ylim(min(agg5[,'Raw Error']-agg5[,'Err bar']), max(agg5[,'Raw Error']+agg5[,'Err bar']))


setEPS()
postscript('plots.eps')
final_figure <- grid.arrange(horizon5, horizon30, ncol = 1)
dev.off()

```
```{r t tests for prudent data sim with myopic estimation vs prudent data sim with prudent estimation}
# horizon 5
prudent_myopic5 <- subset(df5, model_sel_agent == 'myopic_agent' & model_sim_traj == 'prudent_traj',select=c(raw_error))
prudent_prudent5 <- subset(df5, model_sel_agent == 'prudent_agent' & model_sim_traj == 'prudent_traj',select=c(raw_error))
t.test(prudent_myopic5[,"raw_error"],prudent_prudent5[,"raw_error"],var.equal=TRUE)

# horizon 30
prudent_myopic30 <- subset(df30, model_sel_agent == 'myopic_agent' & model_sim_traj == 'prudent_traj',select=c(raw_error))
prudent_prudent30 <- subset(df30, model_sel_agent == 'prudent_agent' & model_sim_traj == 'prudent_traj',select=c(raw_error))
t.test(prudent_myopic30[,"raw_error"],prudent_prudent30[,"raw_error"],var.equal=TRUE)
```


```{r additional ANOVA analysis}
print("Horizon 5")
# my_lm <-lm(raw_error ~ model_sim_traj*model_sel_agent,data=df5)
# summary(my_lm)
model5<-aov(raw_error ~ model_sim_traj*model_sel_agent
            ,data=df5)
summary(model5)
print(model.tables(model5,"means"))
# TukeyHSD(model5)

```



```{r}
print("Horizon 30")
# my_lm <-lm(raw_error ~ model_sim_traj*model_sel_agent,data=df30)
# summary(my_lm)

model30<-aov(raw_error ~ model_sim_traj*model_sel_agent
            ,data=df30)
summary(model30)
print(model.tables(model30,"means"))
# TukeyHSD(model30)
```






